source 'https://rubygems.org'
gem "pact-provider-verifier"
gem "pry"

if ENV['X_PACT_DEVELOPMENT']
  gem "pact-support", path: '../pact-support'
  gem "pact", path: '../pact'
  gem "pact-mock-service", path: '../pact-mock-service'
else
  gem "pact-support", git: "https://github.com/pact-foundation/pact-support.git", ref: "c0c3ad5a92ab02ac0de00d2b0a0d7afeb88095ce"
  gem "pact", git: "https://github.com/pact-foundation/pact-ruby.git", ref: "fa98102843666fd5d334d548ecab9f48257a3ede"
end
